### ISSUE TITLE
일정 preview 생성 시 state 문제 

### ISSUE THREAD

**Issue by seoko97** [JiPyoTak/plandar-client#32]
## :briefcase: **질문 개요**

- 새로운 일정을 생성하거나 기존 일정을 수정하기 위해 mousedown 이벤트를 실행한다면 일정 preview가 생성됩니다.
- 현재 기존일정을 보여주기 위한 `calendarPlanViews`와 일정 preview를 보여주기 위한 `selectedPlanViews` 가 존재합니다.
- 두 state 모두 `IViewPlanInfo[][][]`를 타입으로 가집니다. 
- 데이터 타입이 같은 두 state가 존재할 때 하나의 state만 유지하는 것이 좋을지 여러 state를 사용하는게 좋을지 고민합니다.

```tsx
const CalendarBody = () => {
  ...
    const [calendarPlanViews, setCalendarPlanViews] = useState<IViewPlanInfo[][][]>(getCalendarPlans(dummy, startDate, endDate));
    const [selectedPlanViews, setSelectedPlanViews] = useState<IViewPlanInfo[][][] | null>(null);
  ...
```

**Comment by pyo-sh** [comment]
저는 해당 상태 자체가 실체와 허상을 구분해서 저장한 것이라고 생각하기 때문에 나뉘어져 있는 것이 맞다고 생각합니다.
두 상태를 합치는 것에 대해 고민하셨는데, 합치게 되면 어떤 이점이 있다고 생각하시나요?

**Comment by jintak0401** [comment]
저도 나누어서 관리하는 것이 유지보수와 가독성 측면에서 더 낫다고 생각합니다. 합침으로써 중복된 로직을 줄일 수 있다고 하더라도, 추후에 유지보수를 위해서라면 나누어서 관리하는 것이 더욱 용이해보입니다.

**Comment by seoko97** [comment]
> 저는 해당 상태 자체가 실체와 허상을 구분해서 저장한 것이라고 생각하기 때문에 나뉘어져 있는 것이 맞다고 생각합니다. 두 상태를 합치는 것에 대해 고민하셨는데, 합치게 되면 어떤 이점이 있다고 생각하시나요?

ui/ux 적인 이점이 있습니다. 현재 상태를 나눌경우 선택된 일정에 대해선 정렬을 하지 않고 일정의 가장 최상위 순서로 렌더링되고 있습니다. 만약 두개의 state 합칠경우 새롭게 선택된 일정도 기존 존재하던 일정들의 순서에 영향을 받기 때문에 ui/ux를 조금더 향상 시킬 수 있지 않을까 생각했습니다.

**Comment by jintak0401** [comment]
```tsx
return (
  ...
  { [...selectedPlanViews, ...calendarPlanViews].map((plan) => (...)) }
  ...
);
```

와 같은 형태로는 구현 불가능한가요??

**Comment by seoko97** [comment]
> ui/ux 적인 이점이 있습니다. 현재 상태를 나눌경우 선택된 일정에 대해선 정렬을 하지 않고 일정의 가장 최상위 순서로 렌더링되고 있습니다. 만약 두개의 state 합칠경우 새롭게 선택된 일정도 기존 존재하던 일정들의 순서에 영향을 받기 때문에 ui/ux를 조금더 향상 시킬 수 있지 않을까 생각했습니다.

만약 해당 부분을 두개의 state로 구현할 경우 일정을 드래그 할때마다 `O(6주 * 7일 * 각 날짜에 포함된 일정 n)`의  시간복잡도를 가지게 됩니다.

**Comment by seoko97** [comment]
> ```tsx
> return (
>   ...
>   { [...selectedPlanViews, ...calendarPlanViews].map((plan) => (...)) }
>   ...
> );
> ```
> 
> 와 같은 형태로는 구현 불가능한가요??

두 개의 state는 배열이기 때문에 스프레드 문법은 불가합니다ㅠ

**Comment by pyo-sh** [comment]
> 만약 해당 부분을 두개의 state로 구현할 경우 일정을 드래그 할때마다 O(6주 * 7일 * 각 날짜에 포함된 일정 n)의 시간복잡도를 가지게 됩니다.

UI/UX를 개선한다고 하면, 기존의 존재하던 일정들의 순서에 영향을 받게끔 허상 컴포넌트(드래그)를 구현하기 때문에 당연히 추가되는 시간복잡도라고 생각합니다.
혹 구현로직 상으로 추가적인 계산식이 들어가게 되나요?

**Comment by jintak0401** [comment]
> > ui/ux 적인 이점이 있습니다. 현재 상태를 나눌경우 선택된 일정에 대해선 정렬을 하지 않고 일정의 가장 최상위 순서로 렌더링되고 있습니다. 만약 두개의 state 합칠경우 새롭게 선택된 일정도 기존 존재하던 일정들의 순서에 영향을 받기 때문에 ui/ux를 조금더 향상 시킬 수 있지 않을까 생각했습니다.
> 
> 만약 해당 부분을 두개의 state로 구현할 경우 일정을 드래그 할때마다 `O(6주 * 7일 * 각 날짜에 포함된 일정 n)`의 시간복잡도를 가지게 됩니다.

결국 O(42n) ≈ O(n) 이라고 생각합니다. `42` 라는 숫자는 컴퓨터에게 그렇게 큰 숫자가 아니니까, 이 정도는 충분히 괜찮다고 생각합니다. 체감상 그렇게 성능상 큰 이득을 볼 정도는 아니지 않을까요?

**Comment by seoko97** [comment]
확인했습니다. 확실이 시간복잡도 자체는 예외처리를 한다면 그렇게 큰 연산은 아니라고 생각이 듭니다. 실제 state와 view 데이터를 분리하여 진행을 하되 로직을 추가하는 방식으로 진행하겠습니다. (기존 진행방식과 같습니다.)
