### ISSUE TITLE
일정 생성시 cache update 관련 질문

### ISSUE THREAD

**Issue by seoko97** [JiPyoTak/plandar-client#70]
## :briefcase: **질문 내용**
- 현재 저희 프로젝트에서 일정을 불러올때 시작시간과 종료시간을 통해 일정을 호출합니다.

```ts
useQuery<IPlan[]>(
    ['plans', { timemin, timemax }],
    () => getPlansApi({ timemin, timemax }),
    {
      onSuccess,
    },
  );
```

- 일정 생성 수정시 데이터에 대한 고민은 다음과 같습니다.

```
1. 시작시간/종료시간에 따라 포함되는 모든 cache에 대해 update
2. refetch
```

- 1번을 선택할 경우 해당 일정이 포함되는 `일, 주, 월` cache 데이터를 모두 수정해야합니다.
- 두개의 방법중 어떤 로직을 선택할지 고민입니다.

**Comment by pyo-sh** [comment]
캐싱한 일정이 변경 됐을 때 범위를 고려해서 해당하는 모든 캐싱 데이터를 변경해야 하기 때문에 나온 고민인 것 같습니다.
먼저 저는 일정을 가져오는 API를 React-Query로 사용한다는 것은 Cache를 사용하기 위함으로 받아들이겠습니다.

Refetch를 구현할 때 다음과 같은 방법 등으로 구현할 수 있으나 의문점들이 남습니다.
1. 일정 변경 요청 시 모든 달의 캐싱 삭제 및 재요청
    -> 데이터를 Caching하는 이점이 많이 없어진다고 생각 (상황에 따라 다를 수 있음)
2. 일정에 해당하는 달의 캐싱 삭제 및 재요청
    -> 일정이 어떤 달에 해당하는지 계산하는 과정이 Cache 데이터 수정하는 방안과 비슷함 (비용이 같을 것으로 예상)

따라서 저는 1번인 일정의 Cache 데이터 수정하는 방법이 좋아보입니다.

**Comment by pyo-sh** [comment]
다만 조금의 어려움은 보입니다.
해당 일정이 포함되는 달들의 모든 일정을 훑어야 한다는 것입니다.
제 생각에는 백엔드에서 오는 일정 데이터의 값이 key, value 로 이루어진 객체로 수정하여 가져오는 것이 가장 나을 것 같습니다.
혹은 다른 좋은 방법들이 있다면 더 의논해서 해결하면 좋을 것 같습니다!

**Comment by seoko97** [comment]
일전에 react-query와 비슷한 기능을 수행하는 apollo client를 사용한 경험이 있습니다. 

apollo client는 받아온 데이터의 id값을 cache에 저장하여 여러 캐시가 동일한 데이터 셋을 사용할 경우 해당 id값을 참조하여 항상 같은 데이터 셋을 공유합니다.

```js
plan: {id: 0, ...데이터}

cache { 
  "plan:0": { ...데이터 },
   plans: [ { id: 0, ref: "plan:0" } ]
}
```

다음과 같이 수정할 경우 동일한 데이터셋은 항상 같은 데이터를 참조하게 되므로 일정 수정/생성/삭제시 더 관리하기 용이하다고 판단됩니다.
다음과 같이 데이터를 관리하는 것은 어떨게 생각하시나요?
